export const CATS = [
    {
        id: 0,
        name: "Cat1",
        image: "/assets/images/catToAdopt1.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 1,
        name: "Cat2",
        image: "/assets/images/catToAdopt2.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: true,
    },
    {
        id: 2,
        name: "Cat3",
        image: "/assets/images/catToAdopt3.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: true,
    },
    {
        id: 3,
        name: "Cat4",
        image: "/assets/images/catToAdopt4.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 4,
        name: "Cat5",
        image: "/assets/images/catToAdopt5.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: true,
    },
    {
        id: 5,
        name: "Cat6",
        image: "/assets/images/catToAdopt6.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: true,
    },
    {
        id: 6,
        name: "Cat7",
        image: "/assets/images/catToAdopt7.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 7,
        name: "Cat8",
        image: "/assets/images/catToAdopt8.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 8,
        name: "Cat9",
        image: "/assets/images/catToAdopt9.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 9,
        name: "Cat10",
        image: "/assets/images/catToAdopt10.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 10,
        name: "Cat11",
        image: "/assets/images/catToAdopt11.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 11,
        name: "Cat12",
        image: "/assets/images/catToAdopt12.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
];
