export const CATS = [
    {
        id: 0,
        name: "Buttercup",
        image: "/assets/images/catToAdopt1.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 1,
        name: "Benji",
        image: "/assets/images/catToAdopt2.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: true,
    },
    {
        id: 2,
        name: "Stripes",
        image: "/assets/images/catToAdopt3.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: true,
    },
    {
        id: 3,
        name: "Peanut",
        image: "/assets/images/catToAdopt4.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 4,
        name: "Angel",
        image: "/assets/images/catToAdopt5.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: true,
    },
    {
        id: 5,
        name: "Buddy",
        image: "/assets/images/catToAdopt6.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: true,
    },
    {
        id: 6,
        name: "Ralphy",
        image: "/assets/images/catToAdopt7.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 7,
        name: "Tootsie",
        image: "/assets/images/catToAdopt8.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 8,
        name: "Ivy",
        image: "/assets/images/catToAdopt9.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 9,
        name: "Garfield",
        image: "/assets/images/catToAdopt10.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 10,
        name: "Olivia",
        image: "/assets/images/catToAdopt11.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
    {
        id: 11,
        name: "Meredith",
        image: "/assets/images/catToAdopt12.jpg",
        alt: "Cat that can be adopted",
        info: "Here is some information about the cat. This cat is a great cat and is looking for a loving family.",
        featured: false,
    },
];
