export const DOGS = [
    {
        id: 0,
        name: "Dog1",
        breed: "Breed1",
        image: "/assets/images/dogToAdopt1.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: true,
    },
    {
        id: 1,
        name: "Dog2",
        breed: "Breed2",
        image: "/assets/images/dogToAdopt2.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 2,
        name: "Dog3",
        breed: "Breed3",
        image: "/assets/images/dogToAdopt3.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: true,
    },
    {
        id: 3,
        name: "Dog4",
        breed: "Breed4",
        image: "/assets/images/dogToAdopt4.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 4,
        name: "Dog5",
        breed: "Breed5",
        image: "/assets/images/dogToAdopt5.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: true,
    },
    {
        id: 5,
        name: "Dog6",
        breed: "Breed6",
        image: "/assets/images/dogToAdopt6.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 6,
        name: "Dog7",
        breed: "Breed7",
        image: "/assets/images/dogToAdopt7.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 7,
        name: "Dog8",
        breed: "Breed8",
        image: "/assets/images/dogToAdopt8.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: true,
    },
    {
        id: 8,
        name: "Dog9",
        breed: "Breed9",
        image: "/assets/images/dogToAdopt9.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 9,
        name: "Dog10",
        breed: "Breed10",
        image: "/assets/images/dogToAdopt10.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 10,
        name: "Dog11",
        breed: "Breed11",
        image: "/assets/images/dogToAdopt11.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 11,
        name: "Dog12",
        breed: "Breed12",
        image: "/assets/images/dogToAdopt12.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 12,
        name: "Dog13",
        breed: "Breed13",
        image: "/assets/images/dogToAdopt13.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 13,
        name: "Dog14",
        breed: "Breed14",
        image: "/assets/images/dogToAdopt14.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 14,
        name: "Dog15",
        breed: "Breed15",
        image: "/assets/images/dogToAdopt15.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
    {
        id: 15,
        name: "Dog16",
        breed: "Breed16",
        image: "/assets/images/dogToAdopt16.jpg",
        alt: "Dog that can be adopted",
        info: "Here is some information about the dog. This dog is a great dog and is looking for a loving family.",
        featured: false,
    },
];
