export const DOGS_LOADING = "DOGS_LOADING";
export const DOGS_FAILED = "DOGS_FAILED";
export const ADD_DOGS = "ADD_DOGS";

export const CATS_LOADING = "CATS_LOADING";
export const CATS_FAILED = "CATS_FAILED";
export const ADD_CATS = "ADD_CATS";

export const TESTIMONIALS_LOADING = "TESTIMONIALS_LOADING";
export const TESTIMONIALS_FAILED = "TESTIMONIALS_FAILED";
export const ADD_TESTIMONIALS = "ADD_TESTIMONIALS";
export const ADD_TESTIMONIAL = "ADD_TESTIMONIAL";
