export const InitialAdoptionState = {
    firstName: "",
    lastName: "",
    whichFurBaby: "",
    furBabyType: "",
    areaCode: "",
    phoneNum: "",
    email: "",
    address: "",
    address2: "",
    city: "",
    state: "",
    zipCode: "",
    livingArrangement: "",
    rentOrOwn: "",
    age: "",
    numChildren: "",
    childrenAge: [""],
    petExperienceLevel: "",
    describeExperience: "",
    infoCorrect: false,
    agreeContact: false,
};

export const InitialVolunteerState = {
    firstName: "",
    lastName: "",
    areaCode: "",
    phoneNum: "",
    email: "",
    address: "",
    address2: "",
    city: "",
    state: "",
    zipCode: "",
    age: "",
    infoCorrect: false,
    agreeContact: false,
};
